source ‘https://github.com/CocoaPods/Specs.git’ 
platform :ios, ‘10.0’ 
use_frameworks! 

target 'Team58App' do
pod ‘Alamofire’, ‘~> 4.5’
pod 'Google/SignIn'

end


post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['CLANG_WARN_DOCUMENTATION_COMMENTS'] = 'NO'
        end
    end
end
